---
title: "Allegheny County WPRDC Data Sets Health Check"
output: 
  flexdashboard::flex_dashboard:
    runtime: shiny
    orientation: row
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(shiny)
library(jsonlite)
library(dplyr)
library(DT)
# do de do
# la de da
# Ckan Host url
host <- "data.wprdc.org"

# Find org ID from ckan API: https://data.wprdc.org/api/action/package_search?q=<search-term>
org_id <- "f6dcf8fb-2051-4226-8c74-de9fbc699684"

# Get the users for the organization
users <- reactive({
  data <- fromJSON(paste0("https://", host, "/api/3/action/organization_show?id=", org_id))$result
  users <- data$users
  
  return(users)
})

# Grab all datasets on WPRDC and filter them by org id
dataSets <- reactive({
  data <- fromJSON(paste0("https://", host, "/api/action/package_search?rows=1000&start=0"))$result
  dataSets <- select(data$results, -c(relationships_as_object, relationships_as_subject, extras, groups)) %>%
    flatten() %>%
    filter(organization.id == org_id)%>%
    # Measurements based off publishing frequency
    mutate(metadata_modified = as.POSIXct(metadata_modified, format = "%Y-%m-%dT%H:%M:%S"),
           update_period = case_when(frequency_publishing == "Hourly" ~ 1,
                                     frequency_publishing == "Daily" ~ 24,
                                     frequency_publishing == "Weekly" ~ 7*24,
                                     frequency_publishing == "Monthly" ~ 30*24,
                                     frequency_publishing == "Quarterly" ~ 4*30*24,
                                     frequency_publishing == "Bi-Annually" ~ 6*30*24,
                                     frequency_publishing == "Annually" ~ 365*24,
                                     TRUE ~ NaN
                                     ),
           # Resource link
           title = paste0('<a href="https://', host, '/dataset/', name, '" target="_blank">', title, '</a>'),
           measure_hrs = difftime(Sys.time(), metadata_modified, units = "hours"),
           # Build Alert
           alert = ifelse(measure_hrs >= update_period, 1, 0))
  
  return(dataSets)
})
```

Datasets
===================================== 

Row
-----------------------------------------------------------------------

```{r}
# Data table that shows datasets and update time
DT::renderDataTable({
  dataSets <- dataSets() %>%
    select(title, metadata_modified, department, data_steward_name, frequency_publishing, measure_hrs, alert) %>%
    as.data.frame() %>%
    mutate(measure_hrs = round(measure_hrs, 2)) %>%
    arrange(desc(alert), desc(metadata_modified))
  
  DT::datatable(dataSets, options = list(pageLength = 25), escape = F) %>%
    DT::formatStyle("alert",
                target = 'row',
                backgroundColor = styleEqual(c(1), c("#ef8a62"))
    )
})
```

Users
===================================== 

Row
-----------------------------------------------------------------------

```{r}
# List of users
DT::renderDataTable({
  userTable <- users() %>%
    mutate(name = paste0('<a href="https://data.wprdc.org/organization/member_new/', org_id, "?user=", id, '" target="_blank">', name, '</a>')) %>%
    select(display_name, name, capacity, state, created, number_created_packages, number_of_edits) %>%
    arrange(state, created)
}, options = list(pageLength = 25), escape = FALSE)
```